name = "OptimPack"
uuid = "04a3d532-ba69-5937-989a-472689bdb720"
authors = ["Éric Thiébaut <https://github.com/emmt>"]
version = "1.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OptimPack_jll = "8115cc2e-fb29-5d71-b5cb-a4fb1c5dcd4c"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
OptimPack_jll = "3.4.0"
julia = "1.6"

[extras]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Printf"]
